/**
 * Regenerate src/lib/data/cbs-localities.ts from the CBS settlements file on
 * data.gov.il (resource d47a54ff…, "קובץ היישובים"). Each settlement carries an
 * ITM coordinate; we convert to WGS84 and emit a static code→[lat,lng] map plus a
 * normalized-name index, so geocoding needs no runtime API call.
 *
 *   npx tsx scripts/gen-localities.ts
 */
import { writeFileSync } from "fs";
import { parseCbsCoords } from "../src/lib/data/itm";

const CKAN = "https://data.gov.il/api/3/action/datastore_search";
const CBS = "d47a54ff-87f0-44b3-b33a-f284c0c38e5a";

const normName = (s: string) => s.replace(/["'`׳״\-\s]/g, "");
const round5 = (n: number) => Math.round(n * 1e5) / 1e5;

async function main() {
  const res: { result: { records: Record<string, unknown>[] } } = await (
    await fetch(`${CKAN}?resource_id=${CBS}&limit=2000`, { signal: AbortSignal.timeout(20000) })
  ).json();
  const byCode: Record<string, [number, number]> = {};
  const byName: Record<string, [number, number]> = {};
  let ok = 0;
  for (const r of res.result.records) {
    const c = parseCbsCoords(r["קואורדינטות"]);
    if (!c) continue;
    ok++;
    const ll: [number, number] = [round5(c[0]), round5(c[1])];
    const code = String(r["סמל יישוב"] ?? "").trim();
    const name = String(r["שם יישוב"] ?? "").trim();
    if (code) byCode[code] = ll;
    if (name) byName[normName(name)] = ll;
  }
  const out =
    `// AUTO-GENERATED by scripts/gen-localities.ts from data.gov.il CBS settlements\n` +
    `// (resource d47a54ff…). ${ok} settlements geocoded (ITM→WGS84). Do not edit by hand.\n\n` +
    `export const CBS_BY_CODE: Record<string, [number, number]> = ${JSON.stringify(byCode)};\n\n` +
    `export const CBS_BY_NAME: Record<string, [number, number]> = ${JSON.stringify(byName)};\n`;
  writeFileSync("src/lib/data/cbs-localities.ts", out, "utf8");
  console.log(`✅ wrote src/lib/data/cbs-localities.ts — ${ok} settlements (${Object.keys(byCode).length} codes, ${Object.keys(byName).length} names)`);
  process.exit(0);
}
main().catch((e) => {
  console.error("❌ failed:", e);
  process.exit(1);
});
